apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: vprofileapp
spec: 
  replicas: 1
  selector:
    matchLabels:
        name: tomcatapp
  template: 
    metadata:
      labels:
        name: tomcatapp
    spec: 
      containers:
        -  name: tomcat-container
           image: jeevaa21/app01
           ports: 
           -  name: tomcat-port
              containerPort: 8080
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      
